version: 2

models:
  - name: stg_olist__customers
    description: Customer information for all Olist customers.
    columns:
      - name: order_customer_id
        description: Primary key of table. Key to the orders dataset - each order has a unique customer_id.
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: Unique customer identifier.
        data_tests:
          - not_null
      - name: customer_zip_code
        description: First five digits of customer zip code.
      - name: customer_city
        description: Customer city name.
      - name: customer_state
        description: Customer state.

  - name: stg_olist__orders
    description: Order information for all Olist orders
    columns:
      - name: order_id
        description: Primary key of table. Unique identifier for each order
        data_tests:
          - unique
          - not_null
      - name: order_customer_id
        description: Foreign key to customers. Each order has a unique order_customer_id.
        data_tests:
          - not_null
      - name: order_status
        description: Current status of order
        data_tests:
          - accepted_values:
              values: ['created', 'shipped', 'approved', 'canceled', 'invoiced', 'delivered', 'processing', 'unavailable']
      - name: order_purchase_timestamp
        description: Timestamp when the order was made.
      - name: order_approved_timestamp
        description: Timestamp when the payment was approved.
      - name: order_delivered_carrier_timestamp
        description: Timestamp when order was handed to logistics partner
      - name: order_delivered_timestamp
        description: Timestamp when order was delivered to customer
      - name: order_est_delivery_timestamp
        description: Timestamp for estimated delivery date at the moment of purchase
      - name: minutes_purchase_to_approval
        description: Minutes from time purchase is made to time order is approved.
      - name: minutes_approval_to_carrier
        description: Minutes from time order is approved to the time it is delivered to the customer.
      - name: minutes_carrier_to_delivered
        description: Minutes from time order delivered to carrier to when it is delivered to the customer.
      - name: days_purchase_to_delivery
        description: Days between purchase and delivery to customer.
      - name: days_estimated_vs_actual_delivery
        description: Days between estimated and actual delivery dates. A positive value indicates the order was delivered before its estimated delivery date.

  - name: stg_olist__payments
    description: Payment information for all Olist orders
    columns:
      - name: order_id
        description: Identifier for each order.
        data_tests:
          - not_null
      - name: payment_sequential
        description: Payment in sequence. If a customer pays for an order with more than one payment method then a sequence will be created.
      - name: payment_method
        description: Payment method.
        data_tests:
          - accepted_values:
              values: ['credit_card', 'debit_card', 'voucher', 'boleto', 'not_defined']
      - name: payment_installments
        description: Number of payment installments chosen by the customer.
      - name: payment_value
        description: Transaction value.

  - name: stg_olist__locations
    description: Detailed information for every Brazilian location in the data. Note that the zip code prefix is not unique.
    columns:
      - name: zip_code
        description: Zip code prefix.
        data_tests:
          - not_null
      - name: latitude
        description: Latitude.
        data_tests:
          - not_null
      - name: longitude
        description: Longitude.
        data_tests:
          - not_null
      - name: city
        description: City.
        data_tests:
          - not_null
      - name: state
        description: State.
        data_tests:
          - not_null

  - name: stg_olist__order_items
    description: Information on the individual items contained in each order.
    columns:
      - name: order_id
        description: Order identifier.
        data_tests:
          - not_null
      - name: order_item_id
        description: Sequential identifier indicating the number of items in the order.
        data_tests:
          - not_null
      - name: product_id
        description: Product identfier.
        data_tests:
          - not_null
      - name: seller_id
        description: Seller identifier.
        data_tests:
          - not_null
      - name: shipping_limit_timestamp
        description: Seller shipping limit date for passing the order to the carrier.
        data_tests:
          - not_null
      - name: item_price
        description: Individual item price in order.
        data_tests:
          - not_null
      - name: item_freight_value
        description: Item freight value. If an order has more than one item the freight value is divided between the items.
        data_tests:
          - not_null

  - name: stg_olist__category_translations
    description: Translations of product category names
    columns:
      - name: category_name_portuguese
        description: Portuguese name of product category used in other data sources.
      - name: category_name_english
        description: English translation of product category.

  - name: stg_olist__sellers
    description: Geographic information on all sellers.
    columns:
      - name: seller_id
        description: Primary key. Unique seller identfier. 
        data_tests:
          - unique
          - not_null
      - name: seller_zip_code
        description: First five digits of seller zip code.
      - name: seller_city
        description: Seller city.
      - name: seller_state
        description: Seller state.

  - name: stg_olist__products
    description: Product information for all Olist products.
    columns: 
      - name: product_id
        description: Unique product identifier.
        data_tests:
          - unique
          - not_null
      - name: product_category
        description: Product category (Portuguese).
      - name: product_name_length
        description: Number of characters in product name.
      - name: product_description_length.
        description: Number of characters in product description.
      - name: product_photos_qty
        description: Number of photos in product listing. 
      - name: product_weight_g
        description: Product weight in grams.
      - name: product_length_cm
        description: Product length in centimeters.
      - name: product_width_cm
        description: Product width in centimeters.
      - name: product_height_cm
        description: Product height in centimeters.

