version: 2

models:
  - name: stg_olist__customers
    description: Customer information for all Olist customers.
    columns:
      - name: order_customer_id
        description: Primary key of table. Key to the orders dataset - each order has a unique customer_id.
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: Unique customer identifier.
        data_tests:
          - not_null
      - name: customer_zip_code
        description: First five digits of customer zip code.
      - name: customer_city
        description: Customer city name.
      - name: customer_state
        description: Customer state.

  - name: stg_olist__orders
    description: Order information for all Olist orders
    columns:
      - name: order_id
        description: Primary key of table. Unique identifier for each order
        data_tests:
          - unique
          - not_null
      - name: order_customer_id
        description: Foreign key to customers. Each order has a unique order_customer_id.
        data_tests:
          - not_null
      - name: order_status
        description: Current status of order
        data_tests:
          - accepted_values:
              values: ['created', 'shipped', 'approved', 'canceled', 'invoiced', 'delivered', 'processing', 'unavailable']
      - name: order_purchase_timestamp
        description: Timestamp when the order was made.
      - name: order_approved_timestamp
        description: Timestamp when the payment was approved.
      - name: order_delivered_carrier_timestamp
        description: Timestamp when order was handed to logistics partner
      - name: order_delivered_timestamp
        description: Timestamp when order was delivered to customer
      - name: order_est_delivery_timestamp
        description: Timestamp for estimated delivery date at the moment of purchase

  - name: stg_olist__payments
    description: Payment information for all Olist orders
    columns:
      - name: order_id
        description: Identifier for each order.
        data_tests:
          - not_null
      - name: payment_sequential
        description: Payment in sequence. If a customer pays for an order with more than one payment method then a sequence will be created.
      - name: payment_method
        description: Payment method.
        data_tests:
          - accepted_values:
              values: ['credit_card', 'debit_card', 'voucher', 'boleto', 'not_defined']
      - name: payment_installments
        description: Number of payment installments chosen by the customer.
      - name: payment_value
        description: Transaction value.

  - name: stg_olist__locations
    description: Detailed information for every Brazilian location in the data. Note that the zip code prefix is not unique.
    columns:
      - name: zip_code
        description: Zip code prefix.
        data_tests:
          - not_null
      - name: latitude
        description: Latitude.
        data_tests:
          - not_null
      - name: longitude
        description: Longitude.
        data_tests:
          - not_null
      - name: city
        description: City.
        data_tests:
          - not_null
      - name: state
        description: State.
        data_tests:
          - not_null

