version: 2

models:
  - name: customer_value
    description: Value metrics for customers including all orders and payments they have made through Olist
    columns:
      - name: customer_id
        description: Unique customer identifier.
      - name: completed_order_value
        description: Monetary value of all orders marked 'delivered' or 'invoiced'.
      - name: pending_order_value
        description: Monetary value of all orders marked 'created', 'approved', 'processing', or 'shipped'.
      - name: lost_order_value
        description: Monetary value of all orders marked 'canceled' or 'unavailable'
      - name: number_of_orders
        description: Count of the number of Olist orders made by the customer.
      - name: first_order_date
        description: Earliest order date.
      - name: last_order_date
        description: Most recent order date.

  - name: olist_weekly_sales
    description: Aggregate information on all Olist orders.
    columns:
      - name: order_year
        description: Year order was placed.
      - name: order_week
        description: Week order was placed (0-52).
      - name: number_of_orders
        description: Number of orders.
      - name: sales_value
        description: Cumulative order value.